# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 05:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autotriage', '0016_alter_model_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='logging_dir',
            field=models.CharField(blank=True, help_text='If logging is enabled, what directory should we use to store log files for this queue? If no directory is set, default to /var/log/helpdesk/', max_length=200, null=True, verbose_name='Logging Directory'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='usersettings_autotriage', to=settings.AUTH_USER_MODEL),
        ),
    ]
